- README.md
- playground/app.config.ts
- playground/app.vue
- src/module.ts
- src/runtime/Icon.vue
Replacing icons in big projects can be tedious and it's sometimes hard to remember which exact icon was used for a certain element. With the `aliases` option you can define your own names for icons and easily swap them out in your entire application.
> feat: add aliases option

- README.md
- src/module.ts
- src/runtime/Icon.vue
Adds an option to change the default class of the `<Icon />` component or remove it entirely.
To remove the class entirely:
```ts
// app.config.ts
export default defineAppConfig({
nuxtIcon: {
class: '', // default .icon class is removed
})
```
Resolves #24
> Feature: Add `class` option to `nuxtIcon` config

- README.md
- src/module.ts
- src/runtime/Icon.vue
Adds a headless option to remove `.icon` class from the icon component.
Resolves #24
> feat: Add headless option to nuxtIcon config

- playground/nuxt.config.ts
- src/runtime/Icon.vue
This PR adds autocomplete on aliases on the `name` prop of `Icon.vue`.
It keeps the type permissive as any other string can be a name, but provides suggestions over the known aliases of the `appConfig.nuxtIcon.aliases` key.
> feat: autocomplete aliases

- package.json
- pnpm-lock.yaml
- src/module.ts
Context: https://github.com/nuxt/nuxt/issues/20209#issuecomment-1517625188
Remove deprecated `nuxt-config-schema` and require build-in functionality from nuxt `3.1.0`. 
Since integration is via a hook, we can lower nuxt dependency to `3.0.0` and avoid breaking changes too...
> refactor: remove experimental `nuxt-config-schema`

- README.md
I had to dig around to found out how the change the color of the icons, with this issue solving my query, https://github.com/nuxt-modules/icon/issues/17.
I edited the documentation so it is clearer for future users.
> Add color prop to README.md documentation

- src/runtime/Icon.vue
- src/runtime/IconCSS.vue
Changing the Imports for `ref` `computed` and `watch` to be imported from vue directly instead of `#imports` reason for this change is, that for me, webstorm fails to detect the type of a ref when used with nuxt3's auto import.
I manually disabled the implicit imports for `vue` sadly this has the side effect, that they no longer are available from `#imports` causing this to break, importing them direcly from vue fixes this issue :)
Would apreciate it alot if this gets merged :D
> Import ref, computed & watch from vue instead of #imports

- src/runtime/Icon.vue
This loses the size of my icon, causing the layout to shift, so fix it
> fix(Icon.vue): fix size of element being fetched

- src/runtime/Icon.vue
- src/runtime/IconCSS.vue
fix #103 
* The appConfig type from useAppConfig uses a unknown type as value, this PR set the value for the returned appConfig
``` ts
interface AppConfig {
[key: string]: unknown;
}
```
* Simplify `iconName` computed logic
|Before|After|
|-------|-----|
|![image](https://github.com/nuxt-modules/icon/assets/38621036/b9e27bad-2f6a-4223-9498-83e387ecb5d8)|![image](https://github.com/nuxt-modules/icon/assets/38621036/66150fc5-1f08-44ad-8dfc-364652bdc7ab)|
> fix: add type for unknown appConfig

- README.md
- package.json
- pnpm-lock.yaml
- src/module.ts
- src/runtime/Icon.vue
- src/runtime/IconCSS.vue
Acknowledges #34 
- adds a configuration option for providing a custom Iconify API url, as well as an option to keep the default as fallback
```ts
// app.config.ts
export default defineAppConfig({
nuxtIcon: {
// ...
iconifyApiOptions: {
url: 'https://<your-api-url>',
publicApiFallback: true // default: false
}
}
})
```
- implements an option for GDPR compliance
- adds according documentation
- does not resolve the feature request of offline asset bundling
Calls `addAPIProvider()` from `@iconify/vue` internally. 👉🏻 [Reference](https://iconify.design/docs/icon-components/vue/add-api-provider.html#iconify-for-vue-function-addapiprovider`)
> feat: add iconify API configuration option

- src/runtime/Icon.vue
Resolves #100 
While accessing properties of `nuxtIcon`, the application would throw a `TypeError` if `nuxtIcon` was undefined.
Added optional chaining (`?.`) to safely access the nested properties of `nuxtIcon`.
- Implemented optional chaining to check the existence of `nuxtIcon` before trying to access its `aliases` property.
- This resolves the error: "TypeError: Cannot read properties of undefined (reading 'aliases')".
> fix: support undefined app.config `nuxtIcon`

- src/runtime/Icon.vue
fix #132
Added non-null assertion in `iconName` so that TypeScript can infer the type as `string`, not `string | undefined`.
> fix: add non-null assertion to iconName

- src/runtime/Icon.vue
When using the NuxtIcon (Icon) component in Histoire stories, an error occurs:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'component')
at Icon.vue:71:49` 
Added optional chaining (?.) to component computed:
` ...nuxtApp.vueApp?.component...`
- Implemented optional chaining to check the existence of vueApp in nuxtApp before trying to access.
- This resolves the error: "TypeError: Cannot read properties of undefined (reading 'component')".
clone: https://github.com/RobertHaba/icon/tree/feature/histoire-example
or add Histoire package
**package.json**
```
"devDependencies": {
"@histoire/plugin-nuxt": "^0.17.14",
"@histoire/plugin-vue": "^0.17.14",
"histoire": "^0.17.14",
...
}
```
**histoire.config.ts**
```
import { defineConfig } from "histoire"
import { …
```
> fix(icon): use optional chaining to fix 'undefined' error in Histoire

- playground/app.vue
- playground/base/icons/layer.svg
- playground/base/nuxt.config.ts
- playground/nuxt.config.ts
- src/module.ts
Hello, 
firstly, thank you for this package! I like the new approach of the v1.
Here's a PR to support `customCollections` from layers
It's common to use in layers `const { resolve } = createResolver(import.meta.url)`,
but currently, all `customCollections.dir` paths were prefixed with `nuxt.options.rootDir`
This PR just adds an `isAbsolute` check, and adds a `base` layer in the playground for test purpose
> feat: support custom collections from layers

- README.md
Fix link in readme for the `component` example.
> docs: fix component example url

- src/module.ts
With Nuxt 4 on the horizon, this updates the module compatibility definition to allow it to be installed on Nuxt v4. (Otherwise Nuxt will indicate the module might not be compatible.)
When Nuxt v4 comes out then you might decide or need to make breaking changes in this module and release a new major, but hopefully the migration should be smoother. 🙏 
👉 You can follow this and other changes in https://github.com/nuxt/nuxt/issues/27613 - please feel free to provide feedback as well!
> chore: indicate compatibility with nuxt v4

- src/module.ts
Currently, if there's any issues with custom svgs there's no hints about which one failed, and the whole collection fails to be added.
This fix makes sure that we log any failures and that the successful icons are added.
---
**Before**
---
**After**
> feat: graceful error handling of invalid svgs

- README.md
- src/module.ts
- src/runtime/plugin.ts
- src/schema-types.ts
- src/schema.ts
Closes #185 
Adds a `localApiEndpoint` setting to the module options to allow the default server handler path to be overridden. This is useful in situations where the default `/api` prefix may conflict with existing path-forwarding rules.
> feat: allow local endpoint path to be overridden with `icon.localApiEndpoint`

- src/runtime/components/css.ts
Many modern browsers apply CORS rules to stylesheets. Accessing a stylesheet from a different origin may lead to DOM exceptions. 
It's not uncommon for some browser extensions to inject external stylesheets. Because of this, we should only attempt to pull stylesheets with a `href` of undefined (inline) or the same origin.
I believe this may resolve #189
> fix: don't fail when scanning css rules from external stylesheets

- README.md
- playground/nuxt.config.ts
- src/module.ts
- src/schema.ts
- src/types.ts
- resolve #184 
- resolve #203 
- resolve #188
docs improvements:
- close #205 
- close #178
- close #200
This PR enables the ability to load icon collection data from CDN on the server side instead of loading it from the server bundle. It's called `RemoteCollection`. This would be useful when server bundle size is a concern, under environments like edge functions, or workers. Using a remote source slightly increases the load time of the collections on the first request. The introduction of an external runtime source slightly decreases the stability of the production app as the CDN might get down, and it's not version-controlled.
The default `auto` mode would now be the mode of choice based on the nitro deploy target.
> feat: introduce remote collection

- README.md
- playground/nuxt.config.ts
- src/module.ts
- src/runtime/components/shared.ts
- src/shim.d.ts
- src/types.ts
Partially improve https://github.com/nuxt/icon/issues/34#issuecomment-2241267837
This PR adds the capability of bundling icons to the client bundle. It's currently a manual configuration process, and we will explore the possibility of making it more automated.
> feat: introduce `clientBundle` option

- src/module.ts
resolves #213 
After some digging, I found out that `nuxt.options.nitro.preset` was `undefined` in my cloudflare build environment with zero-config support of nitro, but there's an environment variable `NITRO_PRESET:"cloudflare_pages"` we can use to detect the nitro preset just as nitro doing itself: [unjs/nitro: src/core/config/loader.ts](https://github.com/unjs/nitro/blob/62a74df2cac30fb6e73d4a83959e24daa3bcfa73/src/core/config/loader.ts#L62)
> fix: support nitro preset detection in zero config environments

- src/runtime/components/css.ts
The styles of icons are prepended to head which is not very appropriate.
Screenshots:
> fix: insert styles before first style tag

- src/runtime/components/index.ts
Complement to [#237]
currently it is possible to use option customize only in the Icon component and in nuxt.config.*
currently the priority is:
1. Component Icon
2. nuxt.config.*
with this new fix update the priority is:
1. Component Icon
2. app.config.*
3. nuxt.config.*
> fix: add option customize to app.config and nuxt.config

- src/runtime/server/api.ts
Resolves https://github.com/nuxt/icon/issues/204 (tested against reproduction in https://github.com/nuxt/icon/issues/204#issuecomment-2325095934).
When having multiple versions of `nitropack` installed (reproduction above has one in the playground and one in top level) for some reason rollup keeps `nitropack/runtime` as an external although it shouldn't be. this needs more upstream investigation later)
Using `#imports` seems to fix the issue as it aliases to the explicit path.
> fix: import server utils from `#imports`

- src/runtime/components/shared.ts
- n/a
Added a console.warn for when an icon-load fails due to timeout instead of failing silently. We had an issue where some flag icons wouldn't be loaded due to timeout and it took us quite some time to figure out why it was the case so I thought this could help more people.
> feat: add console warning for icon load timeout

- package.json
- pnpm-lock.yaml
- src/collections.ts
- src/scan.ts
This pull request replaces `fast-glob` with `tinyglobby`.
`tinyglobby` is both [smaller](https://pkg-size.dev/tinyglobby) and uses [less dependencies](https://pkg-size.dev/fast-glob) while keeping the same behavior.
> chore(deps): replace fast-glob with tinyglobby

- src/bundle-server.ts
resolves #276 
People using Deno 2.0 will get an error when running the dev server due to the server bundle not using the `node:` prefix for the `module` core module.
The rest of the codebase uses `node:` prefixes so this would also help with consistency.
> fix: improve deno compatibility by using node specifier in server bundle

- playground/nuxt.config.ts
- src/module.ts
resolves #281
watches changes in files from customCollections directories, and on any change triggers:
- rebuild of client icons bundle 
- rebuild of server icons bundle
- invalidates client bundle in vite dev server 
Potential future improvements (let me know if you're interested, i can create further PR):
- debounce bundles rebuilding in case of rapid file changes
- HMR - probably needs custom message from HMR server to Icon.vue
> feat: Propagate SVG changes in customCollections to client and server bundles without nuxt server restart

- src/runtime/components/css.ts
- src/runtime/components/svg.ts
Configuring classes in app.config.ts may result in two duplicate class names for the component
Removed the passthrough classes from CSS components and SVG components, only using classes in the icon component, resolving the issue of duplication caused by double-layer passthrough in Vue components.
> fix(components): fixed duplicate icon class names

- src/runtime/components/css.ts
- src/runtime/components/svg.ts
N/A
This patch ensures the `customize` option from `app.config` is utilized as a fallback when the `customize` prop is not explicitly provided, further allowing for a global `customize` option.
> fix: fallback to `customize` function from app.config

- README.md
Based from https://github.com/tailwindlabs/tailwindcss/issues/17202, all styles should be inside the base layer otherwise the higher specificity prevents any customisation with CSS. After digging around the codebase, I saw that there is already a provision for this [here](https://github.com/nuxt/icon/blob/main/src/runtime/components/css.ts#L110) that wasn't documented in the README.
> docs: cssLayer for TailwindCSS v4 compatibility

- src/runtime/components/svg.ts
resolves [#356](https://github.com/nuxt/icon/issues/356)
I ran into the issue described [here](https://github.com/nuxt/icon/issues/310) (hydration mismatch warnings caused by @nuxt/icon) and I see a [fix](https://github.com/nuxt/icon/commit/f5e74f592a10da1e0e56dfad137e19baf70f39b8) was developed, but it did not resolve the issue with my app -- the fix appears to have only applied to CSS icons, while I use SVG.
After applying what appeared to be the most simple code change in replicating the CSS-focused fix above to SVG icons, the hydration mismatch issue appears to be resolved. 
Original issue reproduction (my first usage of Stackblitz):
https://stackblitz.com/edit/vitejs-vite-a8edpmzn
Issue resolved when using my fork with the fixes in this PR: …
> fix: apply hydration mismatch bug fix to SVG icons

- README.md
Resolves https://github.com/nuxt/icon/issues/400
I noticed that there wasn't any documentation on configuring Nuxt Icons with the new Nuxt 4 app directory. It took me a while to debug until I realized the issue.
This could be a temporary fix, but the nuxt-icon module can detect the folder structure to determine where the assets directory really is.
> Update README.md to include a Nuxt 4 app dir note

- README.md
[#403 - Highlight the need to use provider: 'server' when using 'nuxt generate'](https://github.com/nuxt/icon/issues/403)
The Nuxt Icon module supports local bundling out-of-the-box, and the client bundle is enabled by default. However, when running nuxt generate, the icon bundles are still being loaded from the Iconify CDN instead of using the local bundles.
The documentation already mentions that when ssr: false, you need to set provider: "server" if you want to use local collections.
Since nuxt generate is equivalent to ssr: false (as it's generating a static site), it would be helpful to mention this in the documentation explicitly.
This clarification would benefit both developers and tools like LLMs, helping to make the integration smoother.
> Highlight the need to set provider: server when using nuxt generate

- src/bundle-client.ts
We dropped this flag for Nuxt v4. As long as the intent here wasn't to check vs. static generation, this should be a safe substitution.
https://github.com/nuxt/ecosystem-ci/actions/runs/15928068917/job/44930076624
> fix: drop use of private `_build` flag

- src/module.ts
resolves #344
It looks like a line of debug code was accidentally committed. This is logging watcher info on dev for all consuming projects.
> fix: clean up debug code
